- type: job
  id: ForemanNCSP
  name: job-name-foreman
  description: job-description-foreman
  playTimeTracker: JobForemanNCSP
  weight: 8
  startingGear: ForemanGear
  alwaysUseSpawner: true
  icon: "JobIconSyndieForeman"
  requireAdminNotify: true
  requirements:
    - !type:WhitelistRequirement
  supervisors: job-supervisors-ncsp
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateSaws
  - SyndicateCommand
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ForemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSaws
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatHardhatSyndicateForeman
    id: ForemanPDA
    ears: ClothingHeadsetNCSP
    outerClothing: ClothingOuterArmorSyndicateForeman
    belt: ClothingBeltUtilityEngineering
    pocket1: WeaponPistolHKUSP
    gloves: ClothingHandsGlovesFingerless
