- type: job
  id: OperativeNCSP
  name: job-name-operative
  description: job-description-operative
  playTimeTracker: JobOperativeNCSP
  weight: 14
  startingGear: OperativeGear
  alwaysUseSpawner: true
  icon: "JobIconSyndieOperative"
  requireAdminNotify: false
  supervisors: job-supervisors-ncsp 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateRamzi
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: OperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSuit
    shoes: ClothingShoesBootsCombat
    id: OperativePDA
    hands: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterCoatSyndieCapArmored
    ears: ClothingHeadsetNCSP
    pocket1: WeaponPistolHKUSP