- type: job
  id: ShipbreakerNCSP
  name: job-name-shipbreaker
  description: job-description-shipbreaker
  playTimeTracker: JobShipbreakerNCSP
  weight: 8
  startingGear: ShipbreakerGear
  alwaysUseSpawner: true
  icon: "JobIconSyndieShipbreaker"
  requireAdminNotify: false
  supervisors: job-supervisors-ncsp
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateSaws
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ShipbreakerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSaws
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatHardhatSyndicate
    id: ShipbreakerPDA
    ears: ClothingHeadsetNCSP
    belt: ClothingBeltUtilityEngineering
    pocket1: WeaponPistolHKUSP
    gloves: ClothingHandsGlovesFingerless
