#ncwl

- type: playTimeTracker
  id: JobKommissarNCWL

- type: playTimeTracker
  id: JobSanitarNCWL

- type: playTimeTracker
  id: JobArtificerNCWL

- type: playTimeTracker
  id: JobDoktorNCWL

- type: playTimeTracker
  id: JobAdministratorNCWL

- type: playTimeTracker
  id: JobKapitanNCWL

- type: playTimeTracker
  id: JobKadetNCWL

#syndicate

- type: playTimeTracker
  id: JobRingleaderNCSP

- type: playTimeTracker
  id: JobLieutenantNCSP

- type: playTimeTracker
  id: JobInfanteerNCSP

- type: playTimeTracker
  id: JobTechnicianNCSP

- type: playTimeTracker
  id: JobRipperdocNCSP

- type: playTimeTracker
  id: JobChemcookNCSP

- type: playTimeTracker
  id: JobOperativeNCSP

- type: playTimeTracker
  id: JobIntelligenceOfficerNCSP

- type: playTimeTracker
  id: JobForemanNCSP

- type: playTimeTracker
  id: JobShipbreakerNCSP

# empire

- type: playTimeTracker
  id: JobFreeholderDSM

- type: playTimeTracker
  id: JobLevymanDSM

- type: playTimeTracker
  id: JobKnightDSM

- type: playTimeTracker
  id: JobCourtierDSM

- type: playTimeTracker
  id: JobAdjutantDSM

- type: playTimeTracker
  id: JobGovernorDSM

#srm

- type: playTimeTracker
  id: JobTenderSRM

- type: playTimeTracker
  id: JobAcolyteSRM

- type: playTimeTracker
  id: JobHunterSRM

- type: playTimeTracker
  id: JobMontagneSRM

- type: playTimeTracker
  id: JobOverseerSRM

#shi

- type: playTimeTracker
  id: JobExecutiveSHI

- type: playTimeTracker
  id: JobBoardSHI

- type: playTimeTracker
  id: JobHighsecSHI

- type: playTimeTracker
  id: JobTraumasecSHI

- type: playTimeTracker
  id: JobSecuritySHI

- type: playTimeTracker
  id: JobEmployeeSHI

- type: playTimeTracker
  id: JobMedtechSHI

#cmm

- type: playTimeTracker
  id: JobOrdnancemanCMM

- type: playTimeTracker
  id: JobMachinistCMM

- type: playTimeTracker
  id: JobPhysicianCMM

- type: playTimeTracker
  id: JobMinutemanCMM

- type: playTimeTracker
  id: JobWatchmasterCMM

- type: playTimeTracker
  id: JobDeputyMarshalCMM

- type: playTimeTracker
  id: JobMarshalCMM