- type: job
  id: Antiquarian
  name: job-name-antiquarian
  description: job-description-antiquarian
  playTimeTracker: JobAntiquarian
  weight: 1
  startingGear: AntiquarianGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  requireAdminNotify: false
  supervisors: job-supervisors-ncsp 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Antiquarian
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: AntiquarianGear
  equipment:
    id: AntiquarianPDA
    ears: ClothingHeadsetGrey
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesFingerless
    jumpsuit: ClothingUniformJumpsuitAntiquarian
    back: ClothingBackpackSatchelLeatherFilled
