- type: job
  id: PhysicianCMM
  name: job-name-physician
  description: job-description-physician
  playTimeTracker: JobPhysicianCMM
  weight: 24
  startingGear: PhysicianGear
  alwaysUseSpawner: true
  icon: "JobIconCMMPhysician"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Minuteman
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: PhysicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMPhysician
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatMinuteman
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    id: PhysicianPDA
    ears: ClothingHeadsetCMM
    pocket1: WeaponPistolHKUSP