- type: job
  id: DeputyMarshalCMM
  name: job-name-deputymarshal
  description: job-description-deputymarshal
  playTimeTracker: JobDeputyMarshalCMM
  weight: 32
  startingGear: DeputyMarshalGear
  alwaysUseSpawner: true
  icon: "JobIconDeputyMarshal"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Minuteman
  - MinutemanPrison
  - MinutemanRankingOfficer
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DeputyMarshalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOfficer
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatCMMDeputyMarshal
    gloves: ClothingHandsGlovesCombat
    belt: WeaponRevolverSnubnose
    id: DeputyMarshalPDA
    ears: ClothingHeadsetCMM
    outerClothing: ClothingOuterArmorCMMDeputyCarapace