- type: job
  id: MachinistCMM
  name: job-name-machinist
  description: job-description-machinist
  playTimeTracker: JobMachinistCMM
  weight: 22
  startingGear: MachinistGear
  alwaysUseSpawner: true
  icon: "JobIconMachinist"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Minuteman
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: MachinistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMMachinist 
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHelmetCMMMachinist
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltUtilityEngineering
    id: MachinistPDA
    ears: ClothingHeadsetCMM
    pocket1: WeaponPistolHKUSP