- type: job
  id: MinutemanCMM
  name: job-name-minuteman
  description: job-description-minuteman
  playTimeTracker: JobMinutemanCMM
  weight: 26
  startingGear: MinutemanGear
  alwaysUseSpawner: true
  icon: "JobIconMinuteman"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Minuteman
  - MinutemanPrison
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: MinutemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMM
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatMinuteman
    gloves: ClothingHandsGlovesCombat
    belt: WeaponPistolHKUSP
    id: MinutemanPDA
    ears: ClothingHeadsetCMM
    neck: ClothingNeckScarfCMMCloak
    outerClothing: ClothingOuterArmorCMM