- type: job
  id: OrdnancemanCMM
  name: job-name-ordnanceman
  description: job-description-ordnanceman
  playTimeTracker: JobOrdnancemanCMM
  weight: 18
  startingGear: OrdnancemanGear
  alwaysUseSpawner: true
  icon: "JobIconOrdnanceman"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Minuteman
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: OrdnancemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOrdnanceman
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHelmetCMMOrdnanceman
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    id: OrdnancemanPDA
    ears: ClothingHeadsetCMM
    pocket1: WeaponPistolHKUSP