- type: job
  id: KapitanNCWL
  name: job-name-kapitan
  description: job-description-kapitan
  playTimeTracker: JobKapitanNCWL
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 16000
  weight: 25
  startingGear: KapitanGear
  alwaysUseSpawner: true
  icon: "JobIconCommsOfficer"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Service
  - External
  - NCWLGeneral
  - NCWLJail
  - NCWLArmory
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: KapitanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWL
    back: ClothingBackpackNCWLFilledSanitar
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatNCWLBeret
    outerClothing: ClothingOuterArmorNCWLCarapaceKapitan
    id: KapitanPDA
    ears: ClothingHeadsetNCWL
    belt: ClothingBeltNCWLWebbing
    pocket1: WeaponPistolHKUSP
    gloves: ClothingHandsGlovesFingerless
  duffelbag: ClothingBackpackDuffelNCWLFilledSanitar
  satchel: ClothingBackpackSatchelNCWLFilledSanitar
