- type: job
  id: GovernorDSM
  name: job-name-governor
  description: job-description-governor
  playTimeTracker: JobGovernorDSM
  requirements:
    - !type:WhitelistRequirement
    - !type:SpeciesRequirement
      allowedOnly:
        - Human
  weight: 87
  startingGear: GovernorGear
  alwaysUseSpawner: true
  icon: "JobIconImperialGovernor"
  requireAdminNotify: true
  supervisors: job-supervisors-imperial
  canBeAntag: false
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External

  - Maintenance
  - EmpireNoble
  - EmpireAdjutant
  - EmpireGovernor
  - EmpireSoldier
  - Service
  - Empire
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: GovernorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialGovernor
    back: ClothingBackpackSatchelLeatherFilledDSM
    shoes: ClothingShoesBootsImperialGovernorBoots
    head: ClothingHeadHatImperialBicorne
    outerClothing: ClothingOuterCoatImperialGovernor
    id: GovernorPDA
    ears: ClothingHeadsetEmpire
    gloves: ClothingHandsGlovesImperialGovernorGloves
    pocket1: ImperialPassportBareLegit
