- type: job
  id: GovernorDSM
  name: job-name-governor
  description: job-description-governor
  playTimeTracker: JobGovernorDSM
  requirements:
    - !type:WhitelistRequirement
    - !type:SpeciesRequirement
      allowedOnly:
        - Human
  weight: 87
  startingGear: GovernorGear
  alwaysUseSpawner: true
  icon: "JobIconImperialGovernor"
  requireAdminNotify: true
  supervisors: job-supervisors-imperial
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - EmpireNoble
  - EmpireAdjutant
  - EmpireGovernor
  - EmpireSoldier
  - Service
  - Empire
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: GovernorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialGovernor
    back: ClothingBackpackSatchelLeatherFilledDSM
    shoes: ClothingShoesBootsImperialGovernorBoots
    head: ClothingHeadHatImperialBicorne
    outerClothing: ClothingOuterCoatImperialGovernor
    id: GovernorPDA
    ears: ClothingHeadsetEmpire
    gloves: ClothingHandsGlovesImperialGovernorGloves
    pocket1: ImperialPassportBareLegit
